[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  port = 8888
  publish = "."

[[redirects]]
  from = "/m-home.html"
  to = "/m-hub.html"
  status = 301

[[redirects]]
  from = "/m-about.html"
  to = "/mobile.html"
  status = 301

[[redirects]]
  from = "/m-services.html"
  to = "/mobile.html"
  status = 301

[[redirects]]
  from = "/m-contact.html"
  to = "/mobile.html"
  status = 301

[[headers]]
  for = "/ipad/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
