[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  port = 8888
  publish = "."

[[redirects]]
  from = "/m-home.html"
  to = "/m-hub.html"
  status = 301

[[redirects]]
  from = "/m-about.html"
  to = "/mobile.html"
  status = 301

[[redirects]]
  from = "/m-services.html"
  to = "/mobile.html"
  status = 301

[[redirects]]
  from = "/m-contact.html"
  to = "/mobile.html"
  status = 301
